//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyanid.VisualStudioExtension.NuGetDeploy {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xyanid.VisualStudioExtension.NuGetDeploy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 full 的本地化字符串。
        /// </summary>
        internal static string DebugInfoFull {
            get {
                return ResourceManager.GetString("DebugInfoFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 none 的本地化字符串。
        /// </summary>
        internal static string DebugInfoNone {
            get {
                return ResourceManager.GetString("DebugInfoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pdbonly 的本地化字符串。
        /// </summary>
        internal static string DebugInfoPdbOnly {
            get {
                return ResourceManager.GetString("DebugInfoPdbOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .dll 的本地化字符串。
        /// </summary>
        internal static string ExtensionDLL {
            get {
                return ResourceManager.GetString("ExtensionDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .pdb 的本地化字符串。
        /// </summary>
        internal static string ExtensionPDB {
            get {
                return ResourceManager.GetString("ExtensionPDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap getFormNuSpec {
            get {
                object obj = ResourceManager.GetObject("getFormNuSpec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap getFormNuSpecDisabled {
            get {
                object obj = ResourceManager.GetObject("getFormNuSpecDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap increase {
            get {
                object obj = ResourceManager.GetObject("increase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap increaseDisabled {
            get {
                object obj = ResourceManager.GetObject("increaseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 0.0.0.0 的本地化字符串。
        /// </summary>
        internal static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;...new...&gt; 的本地化字符串。
        /// </summary>
        internal static string NewEntryIndicator {
            get {
                return ResourceManager.GetString("NewEntryIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 packages.config 的本地化字符串。
        /// </summary>
        internal static string NuGetPackageFilename {
            get {
                return ResourceManager.GetString("NuGetPackageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .nuspec 的本地化字符串。
        /// </summary>
        internal static string NuSpecExtension {
            get {
                return ResourceManager.GetString("NuSpecExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nugetdeploy.config 的本地化字符串。
        /// </summary>
        internal static string ProjectConfigurationFilename {
            get {
                return ResourceManager.GetString("ProjectConfigurationFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FullPath 的本地化字符串。
        /// </summary>
        internal static string PropertyFullpath {
            get {
                return ResourceManager.GetString("PropertyFullpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap saveDisabled {
            get {
                object obj = ResourceManager.GetObject("saveDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 do not use 的本地化字符串。
        /// </summary>
        internal static string UseageNone {
            get {
                return ResourceManager.GetString("UseageNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 use from project 的本地化字符串。
        /// </summary>
        internal static string UseageProject {
            get {
                return ResourceManager.GetString("UseageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 use 的本地化字符串。
        /// </summary>
        internal static string UseageSetting {
            get {
                return ResourceManager.GetString("UseageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
